### ISSUE TITLE
How do I install this with typings?

### ISSUE THREAD

**Issue by tamj0rd2** [rkavalap/npm-nightwatch#6]

**Comment by blakeembrey** [comment]
You can do:

```
typings install nightwatch
```

These definitions can not be published to NPM, we're waiting on https://github.com/Microsoft/types-publisher/issues/4.

**Comment by tamj0rd2** [comment]
Thanks. I've installed this, but intellisense still isn't working in vscode. When I type in `browser.` there is no intellisense

typings.json
```json
{
  "dependencies": {
    "nightwatch": "registry:npm/nightwatch#1.0.0+20170319203500"
  }
}
```

tests/test.spec.js
```js
/// <reference path="../typings/index.d.ts" />

module.exports = {
  'Make sure the tests work': (browser) => {
    browser
      .url('http://google.co.uk')
      .waitForElementVisible('body')
      .end()
  }
}
```

It I take out the `reference path` line, it still doesn't work.

**Comment by tamj0rd2** [comment]
I've also tried using the typings autoinstaller extension but that also hasn't made a difference
